name: Build and deploy

on:
  push:
    branches: [ master ]
    
  # Run workflow manually
  workflow_dispatch:

jobs:
  
  deploy:
    name: Deploy
    
    runs-on: ubuntu-latest
    steps:
      - name: get the source code
        uses: actions/checkout@v2
      - name: install node
        uses: actions/setuo-node@v2
        with:
          node-version: '14'          
      - name: install node package
        run: npm i
      - name: Build
        run: npm run build
          CI: false
      - name: deploy to firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env: 
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          